version: "3"
services:
  # Databases
  postgres:
    image: postgres:12-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./databases/books_db:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/schema.sql:ro

    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: books