apiVersion: apps/v1
kind: Deployment
metadata:
  name: booksvc
  labels:
    app: booksvc
spec:
  replicas: 1
  minReadySeconds: 5
  selector:
    matchLabels:
      app: booksvc
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 2
  template:
    metadata:
      labels:
        app: booksvc
        tier: service
    spec:
      containers:
      - name: booksvc
        image: "alessiomurta/booksvc:latest"
        imagePullPolicy: Always
        resources:
          requests:
            memory: "64Mi"
            cpu: "125m"
          limits:
            memory: "128Mi"
            cpu: "250m"   
        env:
        - name: PORT
          value: "8013"

---
apiVersion: v1
kind: Service
metadata:
  name: booksvc
  labels:
    app: booksvc
    tier: service
spec:
  type: NodePort
  ports:
    - name: http
      port: 8013
      targetPort: 8013
  selector:
    app: booksvc