apiVersion: apps/v1
kind: Deployment
metadata:
  name: booksvc
  labels:
    app: booksvc
spec:
  replicas: 1
  minReadySeconds: 5
  selector:
    matchLabels:
      app: booksvc
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 2
  template:
    metadata:
      labels:
        app: booksvc
        tier: service
    spec:
      containers:
      - name: booksvc
        image: "alessiomurta/booksvc:latest"
        imagePullPolicy: Always
        resources:
          requests:
            memory: "64Mi"
            cpu: "125m"
          limits:
            memory: "128Mi"
            cpu: "250m"
        ports:
        - containerPort: 8013
        readinessProbe:
          httpGet:
            path: /books
            port: 8013
          initialDelaySeconds: 5
          timeoutSeconds: 5
        livenessProbe:
         httpGet:
            path: /books
            port: 8013
          initialDelaySeconds: 5
          timeoutSeconds: 5       
        env:
        - name: PORT
          value: "8013"
---
apiVersion: v1
kind: Service
metadata:
  name: booksvc
  labels:
    app: booksvc
    tier: service
spec:
  type: NodePort
  ports:
  - port: 8013
  selector:
    app: booksvc
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: booksvc
  labels:
    app: booksvc
    tier: backend
spec:
  backend:
    serviceName: booksvc
    servicePort: 8013