apiVersion: apps/v1
kind: Deployment
metadata:
  name: borrowingsvc
  labels:
    app: borrowingsvc
spec:
  replicas: 1
  minReadySeconds: 5
  selector:
    matchLabels:
      app: borrowingsvc
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 2
  template:
    metadata:
      labels:
        app: borrowingsvc
        tier: service
    spec:
      containers:
      - name: borrowingsvc
        image: "alessiomurta/borrowingsvc:latest"
        imagePullPolicy: Always
        resources:
          requests:
            memory: "64Mi"
            cpu: "125m"
          limits:
            memory: "128Mi"
            cpu: "250m"

---
apiVersion: v1
kind: Service
metadata:
  name: borrowingsvc
  labels:
    app: borrowingsvc
    tier: service
spec:
  type: NodePort
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: borrowingsvc
