apiVersion: apps/v1
kind: Deployment
metadata:
  name: customersvc
  labels:
    app: customersvc
spec:
  replicas: 1
  minReadySeconds: 5
  selector:
    matchLabels:
      app: customersvc
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 2
  template:
    metadata:
      labels:
        app: customersvc
        tier: service
    spec:
      containers:
      - name: customersvc
        image: "alessiomurta/customersvc:latest"
        imagePullPolicy: Always
        resources:
          requests:
            memory: "64Mi"
            cpu: "125m"
          limits:
            memory: "128Mi"
            cpu: "250m"
        ports:
        - containerPort: 8014     
        env:
        - name: PORT
          value: "8014"
---
apiVersion: v1
kind: Service
metadata:
  name: customersvc
  labels:
    app: customersvc
    tier: service
spec:
  type: NodePort
  ports:
    - name: http
      port: 8014
      targetPort: 8014
  selector:
    app: customersvc