fullnameOverride: "borrows-mongodb"

image:
  registry: docker.io
  repository: bitnami/mongodb
  tag: 4.4.11-debian-10-r12
  pullPolicy: IfNotPresent
  debug: true

auth:
  enabled: true
  rootPassword: root
  username: root
  password: root
  database: Borrows