// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type Book struct {
	ID      string `json:"id"`
	Title   string `json:"title"`
	Authors string `json:"authors"`
}

type Borrowed struct {
	IDBorrowing string    `json:"idBorrowing"`
	IDCustomer  string    `json:"idCustomer"`
	IDBook      string    `json:"idBook"`
	Starting    time.Time `json:"starting"`
	Expiring    time.Time `json:"expiring"`
	Returned    bool      `json:"returned"`
}

type BorrowedCreate struct {
	IDCustomer *string `json:"idCustomer"`
	IDBook     *string `json:"idBook"`
}

type Customer struct {
	ID      string `json:"id"`
	Name    string `json:"name"`
	Surname string `json:"surname"`
	Nin     string `json:"nin"`
}
