name: Go

on:
  push:

jobs:
  #dbtest:
   # runs-on: ubuntu-latest
    #steps:
     # - uses: actions/checkout@v2
      #- name: Build the stack
       # run: docker-compose up -d
     
  build-booksvc:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: booksvc
    steps:
    - uses: actions/checkout@v2
    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV, 
           echo "COMMIT"=$(git rev-parse --short HEAD) >> $GITHUB_ENV
    - name: Test
      run: |
          echo $RELEASE_VERSION
          echo ${{ env.RELEASE_VERSION }}
          echo $COMMIT
          echo ${{ env.COMMIT }}
    - name: Get branch
      id: get_branch
      run: echo ::set-output name=BRANCH::$(echo $GITHUB_REF)
    - name: Get the commit SHA
      id: get_commit_sha
      run: echo ::set-output name=COMMIT_SHA::$(git rev-parse --short "$GITHUB_SHA")
    - name: Test
      run: |
          echo $COMMIT_SHA
          echo ${{ env.COMMIT_SHA }}
    #- name: Test
     # run: go test -v .
    - name: Build
      run: go build .
    - name: Build and push Docker image
      uses: docker/build-push-action@v1.1.0 
      with:
        path: booksvc/
        dockerfile: booksvc/Dockerfile
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_REPO_PASS}}
        repository: ${{ secrets.DOCKER_USER }}/booksvc
        tags: ${{ steps.get_commit_sha.outputs.COMMIT_SHA }}_${{ env.RELEASE_VERSION}}, latest
        
        
    
          
  build-customersvc:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: customersvc
    steps:
    - uses: actions/checkout@v2
    - name: Get branch
      id: get_branch
      run: echo ::set-output name=BRANCH::$(echo $GITHUB_REF | cut -d / -f 3)
    - name: Get the commit SHA
      id: get_commit_sha
      run: echo ::set-output name=COMMIT_SHA::$(git rev-parse --short "$GITHUB_SHA")
    #- name: Test
     # run: go test -v .
    - name: Build
      run: go build .
    - name: Build and push Docker image
      uses: docker/build-push-action@v1.1.0 
      with:
        path: customersvc/
        dockerfile: customersvc/Dockerfile
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_REPO_PASS}}
        repository: ${{ secrets.DOCKER_USER }}/customersvc
        tags: ${{ steps.get_commit_sha.outputs.COMMIT_SHA }}_${{ steps.get_branch.outputs.BRANCH }}, latest

   
  build-borrowingsvc:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: borrowing
    steps:
    - uses: actions/checkout@v2
    - name: Get branch
      id: get_branch
      run: echo ::set-output name=BRANCH::$(echo $GITHUB_REF | cut -d / -f 3)
    - name: Get the commit SHA
      id: get_commit_sha
      run: echo ::set-output name=COMMIT_SHA::$(git rev-parse --short "$GITHUB_SHA")
    #- name: Test
     # run: go test -v .
    - name: Build
      run: go build .
    - name: Build and push Docker image
      uses: docker/build-push-action@v1.1.0 
      with:
        path: borrowing/
        dockerfile: borrowing/Dockerfile
        username: ${{secrets.DOCKER_USER}}
        password: ${{secrets.DOCKER_REPO_PASS}}
        repository: ${{secrets.DOCKER_USER}}/borrowingsvc
        tags: ${{ steps.get_commit_sha.outputs.COMMIT_SHA }}_${{ steps.get_branch.outputs.BRANCH }}, latest
        build_args: |
          TAG=${{ steps.get_commit_sha.outputs.COMMIT_SHA }}${{ steps.get_branch.outputs.BRANCH }}
