name: Go

on:
  push:

jobs:
  #dbtest:
   # runs-on: ubuntu-latest
    #steps:
     # - uses: actions/checkout@v2
      #- name: Build the stack
       # run: docker-compose up -d
     
  build-booksvc:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: booksvc
    steps:
    - uses: actions/checkout@v2
    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}_"$(git rev-parse --short HEAD) >> $GITHUB_ENV
    - name: Test
      run: |
          echo ${{ env.RELEASE_VERSION }}
    #- name: Test
     # run: go test -v .
    - name: Build Go binary
      run: go build .
    - name: Build and push Docker image
      uses: docker/build-push-action@v1.1.0 
      with:
        path: booksvc/
        dockerfile: booksvc/Dockerfile
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_REPO_PASS}}
        repository: ${{ secrets.DOCKER_USER }}/booksvc
        tags: ${{ secrets.DOCKER_USER }}/booksvc:${{ env.RELEASE_VERSION }},latest
          
          
  build-customersvc:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: customersvc
    steps:
    - uses: actions/checkout@v2
    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}_"$(git rev-parse --short HEAD) >> $GITHUB_ENV
    - name: Test
      run: |
          echo ${{ env.RELEASE_VERSION }}
    #- name: Test
     # run: go test -v .
    - name: Build
      run: go build .
    - name: Build and push Docker image
      uses: docker/build-push-action@v1.1.0 
      with:
        path: customersvc/
        dockerfile: customersvc/Dockerfile
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_REPO_PASS}}
        repository: ${{ secrets.DOCKER_USER }}/customersvc
        build_args: |
          ${{ env.RELEASE_VERSION }}_latest

   
  build-borrowingsvc:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: borrowing
    steps:
    - uses: actions/checkout@v2
    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}_"$(git rev-parse --short HEAD) >> $GITHUB_ENV
    - name: Test
      run: |
          echo ${{ env.RELEASE_VERSION }}
    #- name: Test
     # run: go test -v .
    - name: Build
      run: go build .
    - name: Build and push Docker image
      uses: docker/build-push-action@v1.1.0 
      with:
        path: borrowing/
        dockerfile: borrowing/Dockerfile
        username: ${{secrets.DOCKER_USER}}
        password: ${{secrets.DOCKER_REPO_PASS}}
        repository: ${{secrets.DOCKER_USER}}/borrowingsvc
        build_args: |
          ${{ env.RELEASE_VERSION }}_latest
